<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUq1xZAa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUq1xZAa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUq1xZAa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUq1xZAa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUq1xZAa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uq1xZAa',
    'container.build_id' => 'f7b61260',
    'container.build_time' => 1605964017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUq1xZAa');
